### ISSUE TITLE
Some ARIA parent roles must contain specific child roles to perform their intended accessibility functions. 

### ISSUE THREAD

**Issue by danderson421** [NickDJM/accessible-menu-bootstrap-5#62]
Lighthouse reports new error:

Some ARIA parent roles must contain specific child roles to perform their intended accessibility functions. 

*What are the steps to reproduce this issue?*
1. Go to https://mandrasch.github.io/accessible-menu-bootstrap-examples/bs5-examples/
2. Run Lighthouse
3. See error

![image](https://github.com/NickDJM/accessible-menu-bootstrap-5/assets/372737/97e266d6-ea49-48f2-abec-b76ca35d821a)

**Comment by danderson421** [comment]
.dropdown-menu should probably be role="group" instead of a menubar within a menubar, but I'm not expert.

I believe the issue is that there is a menubar within a menubar when using a dropdown menu

**Comment by NickDJM** [comment]
@danderson421 yup, that's definitely a bug!

Submenus _should_ be role "menu". This is probably an upstream issue, so we'll fix it in accessible-menu and that it'll update here as well.

https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/

**Comment by NickDJM** [comment]
I have the changes pushed up in MRs which I'll merge in shortly and get releases for 3.x and 4.x out.

Here are some screenshots of lighthouse/axe/wave tests with the fix applied (using the demo site in 4.x).

## Lighthouse

![Screenshot from 2023-06-29 11-15-04](https://github.com/NickDJM/accessible-menu-bootstrap-5/assets/6486142/ec2488c3-8b0f-4e40-ac56-9af9d03815d9)

## Axe

![Screenshot from 2023-06-29 11-15-18](https://github.com/NickDJM/accessible-menu-bootstrap-5/assets/6486142/8ee221fd-09ef-4e79-9386-b0bdd5960c8b)

## Wave

![Screenshot from 2023-06-29 11-17-21](https://github.com/NickDJM/accessible-menu-bootstrap-5/assets/6486142/6b370f60-764d-4487-9b18-f11792105980)

**Comment by NickDJM** [comment]
It's probably also worth looking into automated lighthouse tests so prevent these kinds of bugs in the future. I'll need to look into that.

**Comment by danderson421** [comment]
Thanks! Love the script.

**Comment by NickDJM** [comment]
@danderson421 Glad to hear it!

This change is now captured in v1.0.3 (and also in the latest releases of the beta, main accessible-menu project, and the bs4 version).
